import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import grapesjs from "grapesjs";


export default function Home() {
	useEffect(() => {
		grapesjs.init({
			container: "#grape-container",
			plugins: ["gjs-preset-webpage"],
		});
	}, []);
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main id="grape-container" style={{ minHeight: "100vh" }}></main>
		</div>
	);
}
